import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Error from "./error";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="portal"></div>
        <div className="block m-6 space-x-6">
          <Link href="/">Home</Link>
        </div>
        <ErrorBoundary
          children={children}
          errorComponent={Error}
        ></ErrorBoundary>
      </body>
    </html>
  );
}
